# Generated by Django 6.1.1 on 2026-09-13 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveries', '0001_initial'),
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='webhook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhooks.webhook'),
        ),
        migrations.AlterUniqueTogether(
            name='delivery',
            unique_together={('webhook', 'event')},
        ),
    ]
